### ISSUE TITLE
Server crashes when hit by arrow while not wearing holy armor

### ISSUE THREAD

**Issue by MrNoaaan** [TheIllusiveC4/Consecration#25] opened 2018-10-08 22:06 UTC
If a skeleton hits a player with an arrow, and the player is not wearing holy armor(?), the server crashes.
[crash-2018-10-09_00.03.54-server.txt](https://github.com/TheIllusiveC4/Consecration/files/2458167/crash-2018-10-09_00.03.54-server.txt)

**Comment by TheIllusiveC4** [comment] 2018-10-08 22:23
Duplicate of https://github.com/TheIllusiveC4/Consecration/issues/22
Update Consecration to version 0.0.10 or later.

**Closed by TheIllusiveC4** 2018-10-08 22:23 UTC
Labels: duplicate
